"""initial sqlite schema

Revision ID: 1b166bd2be53
Revises:
Create Date: 2025-10-11 18:41:00.346885

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b166bd2be53"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "streams",
        sa.Column("stream_id", sa.String(length=255), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("output_url", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("stream_id"),
    )
    op.create_index(
        op.f("ix_streams_stream_id"), "streams", ["stream_id"], unique=False
    )
    op.create_table(
        "video_merge_tasks",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("source_rtsp_path", sa.String(), nullable=False),
        sa.Column("start_time", sa.String(), nullable=False),
        sa.Column("end_time", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "completed", "error", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("result_video_path", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_merge_tasks")
    op.drop_index(op.f("ix_streams_stream_id"), table_name="streams")
    op.drop_table("streams")
    # ### end Alembic commands ###
